version: '3.3'
services:
  app:
    depends_on:
      - db
    image: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: DEVELOP
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mock_request
      DB_USER: root
      DB_PASSWORD: root
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mock_request
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5434:5432'
