name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Run Node
        uses: actions/setup-node@v2.4.1
      - name: Install dependencies
        run: npm i
      - name: run unit test
        run: npm run test:cov
      - name: run e2e test
        run: npm run test:e2e
