name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.18
      uses: actions/setup-node@v2
      with:
        node-version: 14.18
        cache: 'npm'
    - run: npm ci
    - name: run unit test
      run: npm run test:cov
    - name: run e2e test
      run: npm run test:e2e
